language: php
php:
  - 5.6
  - 7.0

script:
    - mkdir -p build/logs
    - composer install
    - phpunit --coverage-clover build/logs/clover.xml
    - php vendor/bin/coveralls -v

# after_script:
#     - php vendor/bin/coveralls -v
#     - phpunit --coverage-clover build/logs/clover.xml